title: Bookmarklets
description: A list of potentially userful bookmarklets.

highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      status: "draft"
      layout: "post"

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

sass:
  style: compressed
