title: Bookmarklets
description: A list of potentially userful bookmarklets.

highlighter: rouge

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

sass:
  style: compressed
